import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '../components/Navbar';
import { AuthProvider } from './Providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        {/* 'max-w-3xl mx-auto p-4' */}
        {/* <div className='max-w-3xl mx-auto p-4'> */}
        {/* <AuthProvider>{children}</AuthProvider> */}
        {/* <div className=''>{children}</div> */}
        {/* 'mt-8' */}
        {/* <Navbar /> */}
        {/* </div> */}
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
